experiment: 'md-cust-oct-em512-layer8-bs1-flash-2048'

seed: 42
clear_log: False
log_dir: "log/"

midi_dir: "data/midis/"
dataset_save_path: "data/data.csv"
max_example_len: 2048
shuffle: True
dataset_split: [.8, .1, .1]
batch_size: 1
octuple: True
octuple_em_sizes: [1027, 131, 5, 131, 131, 36, 257, 52]

num_heads: 8
d_model: 512
num_layers: 8
ffn_hidden: 256
dropout: 0.1
l_r: 0.001
weight_decay: 0.0001
flash: True

load_path:
debug: False
epochs: 10000
label_smooth: 0.1
model_dir: "saved_models/"
grad_accum: 4